from typing import Any

PY3: bool
StringIO: type
text_type: type[str]

class BaseClass:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def encode_obj(in_obj: Any) -> bytes: ...
def unquote_utf8(qs: str) -> str: ...
